networks:
  fdo_network:
    driver: bridge

volumes:
  # O padrão proficional de persistência é por bind mount, mas para facilitar o uso em ambientes de desenvolvimento
  # e testes que rodam em Windows, utilizamos um "volume nomeado" gerenciado pelo Docker.
  db_data:
  certbot-etc:

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - fdo_network
    ports:
      - "80:80"

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./nginx/nginx.dockerfile
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #   environment:
  #     - NGINX_SERVER_NAME
  #   networks:
  #     - fdo_network
