networks:
  fdo_network:
    external: true

volumes:
  # O padrão proficional de persistência é por bind mount, mas para facilitar o uso em ambientes de desenvolvimento
  # e testes que rodam em Windows, utilizamos um "volume nomeado" gerenciado pelo Docker.
  db_data:
  certbot-etc:

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - fdo_network
