# Roda por padrão caso o usuário rode apenas "docker-compose up" sem especificar o arquivo de configuração.
# Ele é utilizado para sobrescrever ou adicionar configurações específicas para o ambiente de desenvolvimento, sem afetar o ambiente de produção.

services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf

  api:
    ports:
      - "8080:8080"
